Feature/jameszhang878/log in page
TritonSE/MAW-Volunteer-Hub pull request #10
Opened 2022-01-09 22:31 UTC by Cubified

### Administrative Info
[GitHub Issue #5]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added MAW logo and background vectors
- Added form components for log-in/sign-up flows (i.e. full name, email, password, "keep me signed in," "forgot password," etc.)
- Added function to disable the "create account" button based on missing user input

### Testing
How did you confirm your changes worked? 
- We ran the development server, and the web app worked as specified by the mock-up.

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

![1-9-22](https://user-images.githubusercontent.com/8538846/148703687-35dcc022-a5bf-4a43-9685-6656a867fc24.gif)

2022-01-10 20:43 UTC, PatrickBrown1 requested changes
You two did a super good job on your first PR (and like 2 days after I assigned it, serious kudos)! Just a couple of quick changes before I approve.

1. I want to keep the page specific styles separated, so if you could move the logimn specific styles to a new stylesheet, i.e. ./styles/LoginPage.css, that would be awesome (leave the more general styles like color in the index.css). I see you already made the file so just move them over
2. The styling get's a little weird as the screen size starts to shrink. Around 700px width the logo starts to get covered by the login pane.
![image](https://user-images.githubusercontent.com/29768212/148835742-3f21017b-739e-4b6a-94ed-e0e6652c99a2.png)
Ask our designers Andrew / Juliette (maybe make a group dm with both) about what to do in this case, but I think something like centering the login pane and moving the logo to the top is a possible idea.
3. Our VP Technology (Justin) added automatic linting to the repo over the weekend and I just merged it in, so your code should (theoretically) not pass the test cases any more due to linting inconsistencies. Update your branch to the current version of development (be super careful with the merge conflicts because he ran the linting, which means every file was changed) and run the command ```npm run lint-fix``` in the frontend directory. This should automatically lint everything it can (and tell you what you need to change manually).

Shoot me a DM and rerequest my review once you wrap these up. Again, super good job with this PR!

2022-01-12 18:44 UTC, PatrickBrown1 requested changes
Okay it's super close now, the last thing is that it seems the fixed width constants you are using are too big at small screen sizes (less than ~400px it seems to break down because the form is 300px and the padding is 50px). 

i.e.
![image](https://user-images.githubusercontent.com/29768212/149202386-da11635f-985f-4292-bece-83cc07391c89.png)

I think adding one more media query (at say 500px) to make the padding on the form 25px on the sides and the logo size ~300px should fix it. Make sure to check all of the mobile screens to make sure it works (i.e. make sure that the changes I suggested actually work).

2022-01-13 21:08 UTC, PatrickBrown1 approved these changes
Super good job! I'll get one more person to review and merge it in ASAP!

2022-01-13 21:40 UTC, aksharans commented on frontend/src/pages/LoginPage.js
> +          <PasswordField
maybe add className={""} so that its not undefined

2022-01-13 21:54 UTC, aksharans commented on frontend/src/pages/LoginPage.js
> +            type="password"
maybe add className="" so its not undefined in PasswordField

2022-01-13 21:54 UTC, aksharans reviewed
Left a comment and was seeing a couple linting warnings when running, but other than that LGTM

2022-01-14 17:13 UTC, aksharans approved these changes

2022-01-14 18:30 UTC, merged