User Page Templating
TritonSE/MAW-Volunteer-Hub pull request #12
Opened 2022-01-10 23:51 UTC by PatrickBrown1

### Administrative Info
#4 
### Changes
What changes did you make?
- Implemented user page for desktop and mobile views
- Created modals (visually) for change password and delete account

### Testing
How did you confirm your changes worked? 
- Viewed website at different page sizes and at mobile

### Confirmation of Change 
https://user-images.githubusercontent.com/29768212/148857330-aa303fba-7056-4151-9bd3-343f6b57dfb6.mov

2022-01-14 04:14 UTC, JamesZhang878 commented
I only noticed that the modals look a bit cramped with the Galaxy Fold dimensions.
<img width="303" alt="Screen Shot 2022-01-13 at 8 08 51 PM" src="https://user-images.githubusercontent.com/73041370/149450156-fe600871-4ad2-4ad8-ac7f-f21daef35572.png">

Other than that, lgtm.

2022-01-14 04:18 UTC, JamesZhang878 requested changes
I only noticed that the modals look a bit cramped with the Galaxy Fold.
<img width="303" alt="Screen Shot 2022-01-13 at 8 08 51 PM" src="https://user-images.githubusercontent.com/73041370/149450763-6a82affb-c4b3-417a-8ad1-9b2f355ea281.png">

Other than that, lgtm.

2022-01-14 08:47 UTC, aksharans reviewed
Other than James' comment, LGTM

2022-01-14 21:39 UTC, JamesZhang878 approved these changes

2022-01-15 00:04 UTC, aksharans approved these changes

2022-01-15 00:13 UTC, merged