Feature/cubified/wish granting template
TritonSE/MAW-Volunteer-Hub pull request #33
Opened 2022-01-26 20:00 UTC by Cubified

### Administrative Info
[#25]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Added templating for the Wish Granting page, including:
   - Integration with side nav for changing between steps
   - Functional upload, edit, and delete file/category buttons and modals
   - Local persistent filesystem using localStorage
   - More extensible `FileEntry.js` component, exporting more lower-level components in case they need to be used anywhere else in the project

### Testing
How did you confirm your changes worked? 
- Manual testing and verification against the Figma

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| [Demo GIF] |
| --- |
| ![1-26-22](https://user-images.githubusercontent.com/8538846/151237455-c69db659-32dc-4aab-b8b6-22cdb611855d.gif) |

2022-01-26 20:01 UTC, Cubified commented
This isn't urgent, but I want to look more into seeing if I can merge similar modals into a single one -- I will say each of the five modals are just different enough in look/functionality to make this harder than it seems.

2022-01-28 19:19 UTC, PatrickBrown1 requested changes
Looks amazing, merge with development and I'll approve

2022-01-28 21:16 UTC, JamesZhang878 approved these changes

2022-01-29 21:38 UTC, PatrickBrown1 approved these changes
Amazing amazing amazing amazing work 🚀 🔥

2022-01-29 21:38 UTC, merged