Feature/shreyagupta112/created user model integrted passport js and made admin get route
TritonSE/MAW-Volunteer-Hub pull request #34
Opened 2022-01-26 21:44 UTC by shreyagupta112

### Administrative Info
[GitHub Issue #]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes### Administrative Info
[GitHub Issue #]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
Created the model.js, auth.js, scure-routes.js, routes.js, and admin.js files. Model.js is the user schema, admin.js contains a get route which prints out a list of admin or non-admin users, and the other three files deal with authentication.

Testing

### Testing
How did you confirm your changes worked?
I created a few fake users to test out the admin get route and authentication and got it to work locally.

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
I created these files, and haven't submitted any pull requests yet, so the entirety of the files are a new change.

2022-01-27 04:12 UTC, PatrickBrown1 requested changes
I made a lot of changes to the schemas and routes, so now all of the authorization routes are functional. 

The only route left to do is the get users routes.
Can you change the route name to be /getUsers, and take one query param called admin. This query param should be verified as a boolean. If it is true, then it will return all users who are admins. If it is false, it will return all users who are not admins.

2022-01-27 16:02 UTC, mohakvni commented on backend/models/UserModel.js
> +    //  required: true,
I think its better to make verified required

2022-01-27 16:06 UTC, mohakvni reviewed
Looks good to me, apart from the changes Patrick requested, I have added a comment in UserModel for making verified required.

2022-01-30 00:51 UTC, PatrickBrown1 commented
LGTM, will approve when @mohakvni gets a chance to take a look

2022-01-31 03:55 UTC, mohakvni approved these changes
LGTM!

2022-01-31 04:09 UTC, PatrickBrown1 approved these changes

2022-01-31 04:09 UTC, merged