Feature/jameszhang878/mobile side nav
TritonSE/MAW-Volunteer-Hub pull request #41
Opened 2022-02-04 03:33 UTC by JamesZhang878

### Administrative Info
[GitHub Issue #26 ]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Implemented media queries to change styling of side-nav component if width is less than 550px.
- Implemented react indiana drag scroll for side scrolling 

### Testing
How did you confirm your changes worked? 
- I tested the styling with all of the available device sizes in the chrome developer tools

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

https://user-images.githubusercontent.com/73041370/152467562-c8c671a6-32fe-474b-9275-6cf2fe0a0d6b.mov

2022-02-05 00:48 UTC, PatrickBrown1 requested changes
Besides the dropshadow we talked about, looks good. Lmk when you make that change and I will approve

2022-02-05 09:03 UTC, aksharans reviewed
LGTM, only thing I saw was that for the mobile view, the margin top/bottom of the .side_nav_links were extending past the scrollbar container.

2022-02-06 04:15 UTC, PatrickBrown1 approved these changes

2022-02-06 06:35 UTC, aksharans approved these changes

2022-02-07 06:39 UTC, merged