Feature/shreyagupta112/user routes
TritonSE/MAW-Volunteer-Hub pull request #45
Opened 2022-02-18 15:48 UTC by shreyagupta112

### Administrative Info
#38 
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
I created the auth_header.js file and modified the UserRoutes.js file to include new user routes.  I created the auth_header.js file to used by a few user routes.  I created routes to upgrade users to admin and verified by id, a route to get a user's profile by id, and a route to update user information.  The route to upgrade a user to admin requires the logged-in user to be an admin and the route to update user information requires either the logged-in user to be an admin or to be the same user as the one who's information is being edited.

### Testing
How did you confirm your changes worked? 
I used Postman to run each of the user routes.  

### Confirmation of Change 
I created the auth_header.js file.  Everything that isn't the  secure and admin routes has been changed.

| [TODO Screenshot Title] |
| --- |
| [TODO Screenshot Link] |

2022-02-18 22:52 UTC, PatrickBrown1 approved these changes

2022-02-21 20:08 UTC, mohakvni commented on backend/routes/UserRoutes.js
>  router.get("/secure", (req, res, next) =>
Since no longer needed, can be removed!

2022-02-21 20:12 UTC, mohakvni requested changes, later dismissed
Just to sanitize a bit, we can remove the "/secure" route in UserRoutes otherwise everything else, LGTM

2022-02-21 20:20 UTC, mohakvni approved these changes, later dismissed
LGTM

2022-02-21 22:12 UTC, mohakvni commented
So as of now I have found the following errors:
    1. When we try to find user details of user whose Id does not exist in the database, server crashes
    2. When we try to verify a non existent user (ID not in database), does not display appropriate error               but also server does not crash
    3. Server crashed when trying to promote admin of User whose ID not in database
    4. Edit info automatically sets everything to null, if none of the information is passed in request body
    5. Sever crashed when we try to edit information fo non existent ID

2022-02-22 22:32 UTC, mohakvni approved these changes
Tested All possible edge cases, work right about fine! 
LGTM

2022-02-23 18:56 UTC, merged