Added contact card component
TritonSE/MAW-Volunteer-Hub pull request #85
Opened 2022-05-17 01:58 UTC by mohakvni

### Administrative Info
[GitHub Issue #]
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
Added Contact card

### Testing
How did you confirm your changes worked? 
Added to custom 404 page and cross checked

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.
<img width="407" alt="Screen Shot 2022-05-16 at 6 54 29 PM" src="https://user-images.githubusercontent.com/68292499/168712768-00c4d518-d0e2-4c80-aa7f-f7a4eedcd1f6.png">

| [TODO Screenshot Title] |
| --- |
| [TODO Screenshot Link] |

2022-10-29 04:31 UTC, JamesZhang878 requested changes
lgtm. I just noticed one thing when I try to upload an image. I've attached a video of what I see when I try to upload an image. It could just be something that only happens on my machine.

https://user-images.githubusercontent.com/73041370/198813933-e3de5afe-4c12-4e87-8e60-ddfd1f251c3d.mov

2022-10-30 01:40 UTC, aksharans reviewed
lgtm, image cropping seems to be working now. Though not sure if there was supposed to be an additional contacts tab in the navbar (looking at the figma)

2022-10-31 04:16 UTC, JamesZhang878 approved these changes
lgtm

2022-11-02 18:42 UTC, aksharans approved these changes

2022-11-02 18:42 UTC, PatrickBrown1 approved these changes

2022-11-02 18:43 UTC, merged