Profile Deactivation
TritonSE/MAW-Volunteer-Hub pull request #87
Opened 2022-05-25 06:56 UTC by Cubified

### Administrative Info
[GitHub Issue N/A]

### Changes
What changes did you make?
- Added frontend and backend support for deactivating and reactivating accounts
   - Profile page transition/grayscale view
   - Manage page "Deactivated" tab on both desktop and mobile views

### Testing
How did you confirm your changes worked? 
- Manual testing to check for regressions

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

<img width="948" alt="Screen Shot 2022-05-24 at 11 51 17 PM" src="https://user-images.githubusercontent.com/8538846/170199117-8ac5a0b0-2b0d-4723-9d23-2316a4789d86.png">
<img width="942" alt="Screen Shot 2022-05-24 at 11 51 33 PM" src="https://user-images.githubusercontent.com/8538846/170199130-96ebcdd8-0c58-4264-ab70-7ba7adbccf6f.png">
<img width="934" alt="Screen Shot 2022-05-24 at 11 51 40 PM" src="https://user-images.githubusercontent.com/8538846/170199134-0fb15cb8-2e47-434b-88a6-b25cc3b2c531.png">

2022-06-10 17:30 UTC, JamesZhang878 requested changes
LGTM! Only thing I noticed was that when I'm logged in as an admin, and I deactivate an account, I can still edit the roles of the deactivated accounts. Sometimes, this would affect my own roles. There were a couple of times where editing the roles of a deactivated account removed my admin role.

2022-06-14 21:22 UTC, PatrickBrown1 commented
Should merge this into dev branch not current branch

2022-06-15 02:26 UTC, JamesZhang878 approved these changes
lgtm

2022-06-16 02:10 UTC, PatrickBrown1 approved these changes

2022-06-16 02:10 UTC, merged